[mousetrap_julia_binding]
git-tree-sha1 = "11fcbe048ce01f452f275ba03877db122c32185c"

    [[mousetrap_julia_binding.download]]
    url = "http://cords.in-berlin.de/mousetrap_julia_binding.tar.gz"
    sha256 = "4f2b320dee9dd2449f7e1f1a528a3f9cf022bd13f86c6eb0b262d8d1b1ebad1c"

