name: test
on:
  push:
  pull_request:  
defaults:
  run:
    shell: bash
jobs:
    test:
      name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          version:
              - '1.7'
              - '1.9'
          os:
            - macOS-latest
            - windows-latest
            - ubuntu-latest
          arch:
            - x86
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
            show-versioninfo: true
