name: CI
on:
  push:
  pull_request:  
  
defaults:
  run:
    shell: bash
    
jobs:
    test:
      name: Julia ${{ matrix.version }} ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          version:
              - '1.7'
              - '1.9'
          os:
            - macOS-latest
            - windows-latest
            - ubuntu-latest
          arch:
            - x86
          include:
            - os: ubuntu-latest
              prefix: xvfb-run
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
            show-versioninfo: true
        - name: Install Mousetrap
          run: julia --color=yes -e "import Pkg; Pkg.add(url=\"https://github.com/clemapfel/mousetrap_jll\"); Pkg.add(url=\"https://github.com/clemapfel/mousetrap.jl\"); Pkg.precompile()"
        - name: Run Tests
          run: julia -e "import Pkg; Pkg.test(\"Mousetrap\")"
