name: CI
on:
  push:
  pull_request:  
  
defaults:
  run:
    shell: bash
    
jobs:
    test:
      name: Julia ${{ matrix.julia-version }} ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          julia-version:
            - "1.7"
            - "1.9"
          os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
          julia-arch:
            - x64
          include:
            - os: ubuntu-latest
              prefix: xvfb-run
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
            show-versioninfo: true
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
  
    docs:
      name: Documentation ${{ matrix.julia-version }}
      runs-on: windows-latest
      strategy:
        fail-fast: false
        matrix:
          julia-version:
            - "1.7"
            - "1.9"
          julia-arch:
            - x64
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.julia-version }}
            arch: ${{ matrix.julia-arch }}
            show-versioninfo: true
        - uses: julia-actions/julia-buildpkg@v1
        - name: Install Documenter.jl
          run: julia -e "import Pkg; Pkg.add(url=\"https://github.com/JuliaDocs/Documenter.jl\"); Pkg.add(url=\"https://github.com/JuliaDocs/Mousetrap.jl\")"        - name: Build Docs
        - name: Build Docs
          run: julia docs/make.jl
