name: CI
on:
  push:
  pull_request:  
  
defaults:
  run:
    shell: bash
    
jobs:
    test:
      name: Julia ${{ matrix.version }} ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          version:
              - '1.7'
              - '1.9'
              - 'nightly'
          os:
            - macOS-latest
            - windows-latest
            - ubuntu-latest
          arch:
            - x64
          include:
            - os: ubuntu-latest
              prefix: xvfb-run
      steps: 
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
            show-versioninfo: true
        - uses: julia-actions/julia-buildpkg@v1
        - uses: julia-actions/julia-runtest@v1
