name: test
on:
  push:
  pull_request:  
defaults:
  run:
    shell: bash
jobs:
    test:
      name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          version:
              - '1.7'
              - '1.9'
              - 'nightly'
          os:
            - macOS-latest
            - windows-latest
            - ubuntu-latest
          arch:
            - aarch64
            - x86
      steps: 
        - uses: actions/checkout@latest
        - uses: julia-actions/setup-julia@latest
          with:
            version: ${{ matrix.version }}
            arch: ${{ matrix.arch }}
        - run: julia -e "using Pkg; Pkg.status()"
        - uses: julia-actions/julia-buildpkg@latest
        - uses: julia-actions/julia-runtest@latest
